### PR TITLE
pin numpy to versions with py2 support < 1.17

### PR DESCRIPTION
**Pull request by ghost**
Numpy's 1.17 pre-release has dropped support to python 2. See numpy [repo](https://github.com/numpy/numpy/releases/tag/v1.17.0rc1).

This PR is to ensure that the numpy install < v1.17 for py2 and >=v1.17 for py3.

### CODE REVIEW

**Comment by bmerry** [comment]
This isn't necessary. numpy 1.17.0rc1 already provides the necessary package metadata to tell pip that it should not be installed on older versions of Python.

Also note that SARAO SDP is no longer doing any maintenance on PySPEAD. It has been superseded by [spead2](https://github.com/ska-sa/spead2).

**Comment by ghost** [comment]
> Also note that SARAO SDP is no longer doing any maintenance on PySPEAD. It has been superseded by [spead2](https://github.com/ska-sa/spead2).

@bmerry ah okay. Thanks.

**Comment by mmphego** [comment]
@bmerry, perhaps we should archive this repository. What do you think?

**Comment by bmerry** [comment]
> @bmerry, perhaps we should archive this repository. What do you think?

I'm not sure what that means.

**Comment by mmphego** [comment]
> > @bmerry, perhaps we should archive this repository. What do you think?
> 
> I'm not sure what that means.

Live dangerously.
image

**Comment by bmerry** [comment]
Sure, I guess since it can be unarchived at any time it's not really dangerous.

**Pull request closed without merging**
